version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-organizationservice
    restart: always
    environment:
      MYSQL_DATABASE: organizationservice_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
